spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem://localhost/~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
